### ISSUE TITLE
Fallback to other colorscheme when the current colorscheme is not found

### ISSUE THREAD

**Issue by LmanTW** [zaldih/themery.nvim#18]
Sometimes when you uninstall a colorscheme but Themery is still using it, an error will occurs on every startup. To my knowledge, the only fix for now is to delete the `state.json` file. Is it possible for Themery to fallback to other colorscheme when the current one is not found?

**Comment by zaldih** [comment]
Thank you for reporting this problem!

You are right. It is a case that for some reason I did not contemplate.

If anyone wants to work on this, let me know! If not, I'll get to work on it in a few weeks.
