### ISSUE TITLE
Persistance state file not generated

### ISSUE THREAD

**Issue by Shimoon** [zaldih/themery.nvim#19]
After the recent persistance update, I deleted the required item but when I try to set a colorscheme I get the folowing message : "**Themery error: Could not open file for writing: C:\Users\\<user_name>\AppData\Local\nvim-data/themery/state.json**".

I tried to reinstall Themery for it to auto generate the state.json file but it doesn't seems to work either.
Do I need to create it by hand? If so, what should I put in it in order to make it work ?

**Comment by zaldih** [comment]
Thank you for reporting the problem!

@uwla  has it also happened to you on Windows OS?

**Comment by Shimoon** [comment]
> Create an empty file in that location, this should work.

Okay, for some reasons, adding the `themery` folder in `nvim-data` works but not if I directly add an empty `state.json` file.

**Comment by baroldgene** [comment]
I had this issue as well.  I deleted the existing `state.json` file then reloaded and it worked. Would be nice if the plugin could automatically ensure that the themes are removed and regenerate the state file when necessary.

**Comment by zaldih** [comment]
I have just commited a [new change](https://github.com/zaldih/themery.nvim/commit/bb80d0e94149909573d8cd7a575ad2e94389a2ad) that should solve this problem. **Could you check it?** (updating the plugin from the main branch).

**Comment by zaldih** [comment]
If this error persists, do not be afraid to reopen it!
