### ISSUE TITLE
Feature Request: Expose a `setColorScheme` function.

### ISSUE THREAD

**Issue by Razkaroth** [zaldih/themery.nvim#24]
First of all, thanks for the plugin! It is really nice.

The preview feature is really nice, but unless I'm missing something, its either: 
- Register all colorschemes (what i did)
  - Pro: you can explore and pick whatever you fancy
  - Con: you have to deal with the whole list when sometimes you just want to go to a particular theme.
- Register only your preferred colorschemes:
  - Pro: the process of changing colorscheme is now a quicker task
  - Con: Can no longer _explore_ the available options

I think a `setColorScheme( name: string )` function could be enough so people can implement their keymaps and solutions.

**Comment by zaldih** [comment]
To expose this kind of functions, it would be a good idea to add a prefix to distinguish between other commands and add context? For example, `THsetColorScheme()` or `TgetColorschemes()`.

**Comment by Razkaroth** [comment]
Considering that you have to require the plugin to get to the function I
don't think a prefix is needed.

**Comment by zaldih** [comment]
@Razkaroth What do you think of #26?

**Comment by Razkaroth** [comment]
Hi!, just left a couple of comments on the commit. 

Nice work!

**Comment by zaldih** [comment]
Thank you!

If you have left any comments on the PR, I can't see them. Can you confirm that you have left them?
