### ISSUE TITLE
The switcher UI stays open even when inactive

### ISSUE THREAD

**Issue by eldar** [zaldih/themery.nvim#28]
I don't know how I wound up in this state, but the pop up remained open after I supposedly closed it. You can see this on the attached screencast where I navigate inside the buffer with the UI painted on top of it:

[Screencast_20240825_085204.webm](https://github.com/user-attachments/assets/49e00421-4a2f-43b2-9604-09c233c28ce0)

**Comment by zaldih** [comment]
Thanks for reporting it!

This was a problem I had seen once when clicking outside the selector but I forgot about it.

**It should be fixed now with the commit** eb8e95e 🎉 

If you still have problems, feel free to reopen the issue :)
