### ISSUE TITLE
After selecting a colorscheme from the list, nvim print an error "Could not open file for read"

### ISSUE THREAD

**Issue by alexya** [zaldih/themery.nvim#9]
macOS: Sonoma 14.4.1
MacBook Pro: M3 Pro
Neovim: 0.9.5

error message after I select a colorscheme from the list:
```
Themery error: Could not open file for read: /Users/yanqzh/.config/nvim/v:null
```
<img width="755" alt="image" src="https://github.com/zaldih/themery.nvim/assets/2831220/003b1b8f-c4f4-4db6-9217-3c79fc026ddb">

My colorscheme.lua file content:
```
return {
  "zaldih/themery.nvim", -- a plugin to show a list to switch colortheme
  -- event = "VeryLazy",
  config = function()
    local themery = require("themery")
    themery.setup({
      themes = {
        "modus",
        "tokyonight",
        "everforest",
        "vscode",
        "visual_studio_code",
      },
    })
  end,
}
```

**Comment by noahgorstein** [comment]
Hit the same error just yesterday actually. You need to create a lua file in your config for the plugin to write to and persist to.  It should contain these contents IIUC:

```
-- Themery block
  -- This block will be replaced by Themery.
-- end themery block
```

More info in the docs: https://github.com/zaldih/themery.nvim?tab=readme-ov-file#persistence 

Then in your setup, add the `themeConfigFile` option to the table given to `themery.setup` with the path to that file with the Themery block shared above:

Here's my config using Lazy:

```lua
return {
	'zaldih/themery.nvim',
	priority = 1000,
	opts = {
		themes = {
			{
				name = "tokyonight",
				colorscheme = "tokyonight",
				before = [[
				vim.opt.background = "dark"
				require("lualine").setup({
					options = {
						theme = "tokyonight",
					},
				})
			]]
			},
			{
				name = 'kanagawa',
				colorscheme = "kanagawa",
				before = [[
				vim.opt.background = "dark"
				require("lualine").setup({
					options = {
						theme = "kanagawa",
					},
				})
			]]
                       }
		},
		themeConfigFile = "~/.config/nvim/lua/settings/theme.lua",
	},
}
```

One thing I have noticed and if I can't solve it, ill probably open an issue is that I don't see that persistence file really doing anything. It gets written with my last selection, but it doesn't seem to load a colorscheme from there. Curious if you'll have the same experience after adding a config file.

**Comment by Anthony-Heredia-Garcia** [comment]
I also have the same issue (using lazy) with the persistence file not making a difference. I'm successfully writing to it when I select from the menu, but when I reload neovim, it goes back to my default colorscheme. I'm still very new to Neovim as a whole, so here is how I set up the table:
```lua
  {
    'zaldih/themery.nvim',
    config = function()
      local themery = require 'themery'
      themery.setup {
        themes = {
          'kanagawa-lotus',
          'kanagawa-wave',
          'kanagawa-dragon',
          'blue',
          'darkblue',
          'default',
          'delek',
          'desert',
          'elflord',
          'evening',
          'habamax',
          'industry',
          'koehler',
          'lunaperche',
          'morning',
          'murphy',
          'pablo',
          'peachpuff',
          'quiet',
          'ron',
          'shine',
          'slate',
          'torte',
          'zellner',
        },
        themeConfigFile = '~/.config/nvim/lua/theme.lua',
        livePreview = true,
      }
    end,
  },

```

**Comment by zaldih** [comment]
Thank you for opening this issue!

@alexya You seem to be missing the "persistence" part. Please could you try what they suggest (if you still have the problem after adding `themeConfigFile` or need more help let us know).

@noahgorstein @Anthony-Heredia-Garcia 
I realised I didn't clarify this in the readme so I will update it these days.
**The persistence file must be imported** into the neovim configuration (something like `require('settings/theme')`) so that neovim can load the instructions on startup. Confirm me if that works :)

**Comment by noahgorstein** [comment]
works like a charm! Thanks @zaldih !

**Comment by Anthony-Heredia-Garcia** [comment]
@zaldih I also got it working now that I'm importing the file! Thanks for the help!

**Comment by ha5h6r000wn** [comment]
Never mind, i've figured it out. Just add require("settings.theme") to init.lua and then it works.

**Comment by zaldih** [comment]
Readme updated.

If you have any problems, don't hesitate to open a issue!
